# Generated by Django 4.2.1 on 2023-09-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="full_name",
            field=models.CharField(default="Name", max_length=100),
            preserve_default=False,
        ),
    ]
